import type { BotStrategy } from "./types";

export const FALLBACK_STRATEGIES: BotStrategy[] = [
  {
    id: "seykota-ema",
    name: "Seykota EMA v3.5 Bot",
    description: "EMA 15/60 + MA200 하락장 필터 + ADX + RSI + ATR 동적손절 — ChatGPT 5차 리뷰 완료",
    strategyDetail: {
      summary: "Ed Seykota의 추세추종 철학을 v3.5로 업그레이드. ChatGPT 5차 리뷰(25건 수정) 완료. 포지션 복구 시 진입가 보존(reconcile) + 티커 변경 감지, 실제 체결가 사용(UUID 조회 3회 재시도), 마감 일봉 기준 진입 신호, 멀티코인 전체 잔고 스캔 + 다중 보유 경고, INVEST_RATIO 반영, RSI NaN 방지, ATR Wilder 통일. 12년(2013~2026) 백테스트 +23,367%, PF 7.89.",
      regimes: [
        { name: "📈 매수: Golden Cross", condition: "EMA15 > EMA60 크로스 + ADX > 15 + RSI 35~75 + MA200 위", action: "INVEST_RATIO(95%) 매수" },
        { name: "📈 매수: Pullback", condition: "상승추세 중 EMA15 터치 후 반등 + ADX/RSI 필터", action: "INVEST_RATIO 매수 (눌림목)" },
        { name: "🔴 청산: ATR 손절", condition: "가격 < 평균진입가 - ATR × 3.0", action: "전량 매도" },
        { name: "🔄 청산: 트레일링", condition: "10% 수익 후 고점 - ATR × 4.0 하회", action: "전량 매도 (이익 보호)" },
        { name: "📉 청산: 추세 반전", condition: "EMA15 < EMA60 + RSI < 35", action: "전량 매도" },
        { name: "⛔ 매수 차단: 하락장", condition: "가격 < MA200", action: "현금 보유 (하락장 진입 방지)" },
        { name: "⛔ 매수 차단: 이벤트", condition: "CPI/FOMC 발표 전후", action: "Event Guard 차단" },
        { name: "⏸️ 대기", condition: "ADX < 15 또는 RSI 영역 이탈", action: "현금 보유" },
      ],
      entryConditions: [
        { label: "빠른 EMA", value: "15일" },
        { label: "느린 EMA", value: "60일" },
        { label: "하락장 필터", value: "MA200 아래면 매수 차단" },
        { label: "ADX 필터", value: "> 15 (추세 강도)" },
        { label: "RSI 필터", value: "35~75" },
        { label: "거래량 필터", value: "20일 평균 50% 미만이면 차단" },
        { label: "멀티코인", value: "BTC/ETH 중 20일 모멘텀 최강 선택" },
        { label: "포지션 크기", value: "INVEST_RATIO × 잔고 (기본 95%)" },
        { label: "타임프레임", value: "일봉 (진입 신호 1회/일)" },
      ],
      riskManagement: [
        { label: "방향", value: "롱(매수)만 — 현물 전략" },
        { label: "손절", value: "ATR × 3.0 (Wilder smoothing)" },
        { label: "트레일링", value: "10% 수익 시 활성화, ATR × 4.0" },
        { label: "추세 반전 청산", value: "EMA 역전 + RSI < 35" },
        { label: "체결가 기준", value: "주문 UUID로 실제 평균체결가 조회" },
        { label: "수수료", value: "0.1% (빗썸)" },
        { label: "Chart AI", value: "BTCUSDT 차트 AI 신호 보조 (수익 2% 이상 시 조기 청산)" },
        { label: "Event Guard", value: "CPI/FOMC 발표 전후 진입 차단" },
      ],
      feeStructure: [
        { label: "빗썸 거래 수수료", value: "0.1% (매수+매도 각각)" },
        { label: "슬리피지", value: "시장가 주문 기준 약 0.05~0.1%" },
      ],
      backtestResults: [
        { period: "전체: 2013~2026 (12년)", returnPct: "+23,367%", winRate: "56.7%", sharpe: "—", mdd: "-58.4%" },
        { period: "P1: 2025.01~08 (상승장)", returnPct: "+43.1%", winRate: "50%", sharpe: "—", mdd: "—" },
        { period: "P2: 2025.09~26.03 (하락장)", returnPct: "+8.3%", winRate: "50%", sharpe: "—", mdd: "—" },
        { period: "최근 1년", returnPct: "거래 0건 (MA200 하락장 필터)", winRate: "—", sharpe: "—", mdd: "0%" },
        { period: "PF / 거래 수", returnPct: "PF 7.89 / 30건 (12년)", winRate: "Avg Win +61.9% / Avg Loss -10.3%", sharpe: "—", mdd: "—" },
      ],
      liveExpectation: {
        pythonReturn: "12년 백테스트 +23,367% (BTC 233배, ETH 45배)",
        websiteReturn: "빗썸 일봉 데이터 기준 Python 백테스트",
        expectedReturn: "큰 추세에서 크게 먹고(+45~285%), 손실은 작게(-3~10%) 제한",
        reasons: [
          "P1 몬스터 트레이드: 2024.12→2025.02 +45.67% (TRAIL) — 큰 추세 한 번에 크게 먹음",
          "P2 하락장에서도 +8.3%: 숏 없이 현물만으로 소폭 수익",
          "MA200 하락장 필터: 가격 < MA200이면 매수 차단 → 2022 크립토 윈터 완벽 방어",
          "12년 PF 7.89: $1 손실당 $7.89 수익 — 압도적 손익비",
          "Avg Win +61.9% vs Avg Loss -10.3%: 승률 57%로도 장기 복리 성장",
          "2017 불장 +285%, 2021 불장 +157% — 대세 상승장에서 극적 수익",
          "ChatGPT 5차 리뷰 완료: 25건 버그 수정 (체결가, 포지션복구, 티커전환, 마감봉, 다중보유, 주문통합 등)",
        ],
        caveats: [
          "최근 6개월~1년 거래 0건 — MA200 하락장 필터 작동 중 (현금 보유)",
          "롱(매수)만 가능 — 하락장 수익은 0% (손실도 0%)",
          "MDD -58% (2018) — 장기 보유 시 큰 낙폭 감내 필요",
          "일봉 전략 — 급변 시 대응 지연 (15분 모니터링으로 보완)",
          "김치프리미엄 영향 — Chart AI(USDT) 신호와 빗썸(KRW) 가격 괴리 가능",
          "다음 상승장까지 대기 필요 — 기회비용 발생",
        ],
      },
    },
    asset: "BTC/KRW",
    exchange: "Bithumb",
    status: "active",
    startDate: "2026-01-20",
    initialCapital: 3500000,
    currentValue: 3500000,
    totalReturn: 0,
    monthlyReturn: 0,
    maxDrawdown: 0,
    sharpeRatio: 0,
    winRate: 0,
    totalTrades: 0,
    profitTrades: 0,
    lossTrades: 0,
    avgWin: 0,
    avgLoss: 0,
    profitFactor: 0,
    dailyPnL: [],
    monthlyReturns: [],
    recentTrades: [],
  },
  {
    id: "ptj-200ma",
    name: "PTJ Trading v4.8 Bot",
    description: "EMA100 + ATR 밴드 + MA200 하락장 필터 + RSI + ROC20 + 3단계 청산 — ChatGPT 5차 리뷰 완료",
    strategyDetail: {
      summary: "Paul Tudor Jones의 200MA 추세추종을 EMA100 + ATR 밴드 돌파 전략으로 발전. ChatGPT 5차 리뷰 완료(v4.2→v4.7, 총 20건+ 수정). basis_unknown 평단 불명 격리, 다중 보유 즉시 중지, 마감봉 1회 분석, INVEST_RATIO 반영. 12년 백테스트 BTC +28,239%, ETH +22,859%.",
      regimes: [
        { name: "🟢 매수: Band Breakout", condition: "가격 > EMA100+ATR + ROC20 > 0 + RSI 35~75 + MA200 위", action: "INVEST_RATIO 매수" },
        { name: "🟢 매수: RSI 반등", condition: "EMA100 위 + RSI 30 상향돌파 + MA200 위 + 쿨다운 OK", action: "재진입 매수" },
        { name: "🔴 청산: 고정 손절", condition: "PnL ≤ -7%", action: "전량 매도" },
        { name: "🔴 청산: ATR 손절", condition: "가격 < 진입가 - ATR×3.0", action: "전량 매도" },
        { name: "🔄 청산: 트레일링", condition: "8% 수익 후 고점 -10% 하회", action: "전량 매도" },
        { name: "📉 청산: Band+RSI", condition: "가격 < EMA100-ATR + RSI < 35", action: "전량 매도" },
        { name: "⛔ 매수 차단", condition: "가격 < MA200 또는 MA200 데이터 부족", action: "현금 보유" },
      ],
      entryConditions: [
        { label: "EMA", value: "100일 (추세 기준)" },
        { label: "ATR 밴드", value: "ATR × 1.0 (돌파 진입)" },
        { label: "MA200", value: "하락장 필터 (NaN이면 차단)" },
        { label: "RSI", value: "35~75 (과열 회피)" },
        { label: "ROC20", value: "> 0 (모멘텀 양수)" },
        { label: "거래량", value: "20일 평균 50% 이상" },
        { label: "멀티코인", value: "BTC/ETH 20일 모멘텀 최강 선택" },
        { label: "포지션", value: "INVEST_RATIO × 잔고 (기본 95%)" },
      ],
      riskManagement: [
        { label: "방향", value: "롱만 — 현물 전략" },
        { label: "고정 손절", value: "-7%" },
        { label: "ATR 손절", value: "ATR × 3.0" },
        { label: "트레일링", value: "8% 수익 후 활성화, 고점 -10%" },
        { label: "쿨다운", value: "2시간 (재진입 대기)" },
        { label: "수수료", value: "0.2% (코인원)" },
        { label: "평단 불명", value: "basis_unknown 플래그 → SL/TS/PnL 전부 비활성" },
      ],
      backtestResults: [
        { period: "BTC 전체 (2013~2026)", returnPct: "+28,239%", winRate: "50.0%", sharpe: "—", mdd: "-45.2%" },
        { period: "ETH 전체 (2016~2026)", returnPct: "+22,859%", winRate: "43.6%", sharpe: "—", mdd: "-56.7%" },
        { period: "P1: 2025.01~08", returnPct: "-10.93%", winRate: "0/1", sharpe: "—", mdd: "SL (142M→126M)" },
        { period: "P2: 2025.09~26.03", returnPct: "+16.52%", winRate: "1/1", sharpe: "—", mdd: "TRAIL (133M→155M)" },
        { period: "P1+P2 복리 순합계", returnPct: "+3.41%", winRate: "1/2", sharpe: "—", mdd: "(1-10.93%)×(1+16.52%)" },
        { period: "PF", returnPct: "BTC 4.23 / ETH 3.68", winRate: "AvgWin +44~50% / AvgLoss -10%", sharpe: "—", mdd: "—" },
      ],
      liveExpectation: {
        pythonReturn: "BTC 12년 +28,239% (282배), ETH +22,859% (228배)",
        websiteReturn: "빗썸 일봉 기준 Python 백테스트",
        expectedReturn: "큰 추세에서 크게 먹고 (+44%), 손실 작게 (-10%) 제한",
        reasons: [
          "P2 +16.52% TRAIL: $133M→$155M 추세 포착 성공",
          "MA200 하락장 필터: 2022 크립토 윈터 완벽 방어",
          "BTC PF 4.23: $1 손실당 $4.23 수익",
          "3단계 청산: 고정SL → ATR SL → 트레일링 → Band+RSI",
          "ChatGPT 5차 리뷰: 런타임 버그, basis_unknown, 다중보유 등 20건+ 수정",
        ],
        caveats: [
          "P1 -10.93% 손절 1건 — 상승 초기 노이즈에 잡힘",
          "최근 거래 적음 — MA200 하락장 필터 작동 중",
          "MDD -45% (BTC), -57% (ETH) — 장기 낙폭 감내 필요",
          "체결 확인 잔고 기반 — 코인원 API 한계",
        ],
      },
    },
    asset: "BTC/KRW",
    exchange: "Coinone",
    status: "active" as const,
    startDate: "2026-01-20",
    initialCapital: 2500000,
    currentValue: 2500000,
    totalReturn: 0,
    monthlyReturn: 0,
    maxDrawdown: 0,
    sharpeRatio: 0,
    winRate: 50.0,
    totalTrades: 0,
    profitTrades: 0,
    lossTrades: 0,
    avgWin: 44.05,
    avgLoss: 10.40,
    profitFactor: 4.23,
    dailyPnL: [],
    monthlyReturns: [],
    recentTrades: [],
  },
  {
    id: "bybit-alpha-v4",
    name: "Alpha v5 Bot",
    description: "레짐감지 + BULL 숏차단 + 트레일링 강화 — BTC 선물 3x",
    strategyDetail: {
      summary: "BTC 일봉 레짐(BULL/BEAR/SIDEWAYS/DANGER)을 판단하고, BULL에서 롱만, BEAR에서 숏만 진입하는 선물 봇. v4 대비 BULL 숏 차단 + 트레일링 50% 반환으로 개선. 하락장 방어력이 핵심 가치.",
      regimes: [
        { name: "🟢 BULL", condition: "MA50>MA200, 가격>MA50, ROC30>5%", action: "롱만 진입 (숏 차단)" },
        { name: "🔴 BEAR", condition: "MA50<MA200, 가격<MA50, ROC30<-3%", action: "숏만 진입" },
        { name: "⏸️ SIDEWAYS", condition: "위 조건 미충족", action: "거래 차단" },
        { name: "⚠️ DANGER", condition: "ATR z-score > 2.0", action: "전량 청산" },
      ],
      entryConditions: [
        { label: "BULL 롱", value: "ADX > 25 + RSI > 45" },
        { label: "BEAR 숏", value: "ADX > 25 + RSI < 55" },
        { label: "레버리지", value: "3x" },
        { label: "SL/TP", value: "ATR × 2.0 / ATR × 4.0" },
      ],
      riskManagement: [
        { label: "v5 개선", value: "BULL에서 숏 완전 차단 (v4: 허용)" },
        { label: "트레일링", value: "수익의 50% 반환 시 청산 (v4: 30%)" },
        { label: "포지션", value: "자본의 2% 리스크" },
      ],
      backtestResults: [
        { period: "2025.1~8 (상승장)", returnPct: "+0.03%", winRate: "50%", sharpe: "0.07", mdd: "-1.58%" },
        { period: "2025.9~2026.3 (하락장)", returnPct: "0.00%", winRate: "-", sharpe: "-", mdd: "0.00%" },
        { period: "v4 대비", returnPct: "+0.03% vs -2.53%", winRate: "-", sharpe: "-", mdd: "-1.58% vs -3.69%" },
      ],
      liveExpectation: {
        pythonReturn: "합산 +0.03% (v4: -2.53% 대비 개선)",
        websiteReturn: "백테스트 도구에서 확인",
        expectedReturn: "MDD 극소 (-1.58%), 하락장 완벽 방어",
        reasons: [
          "BULL 숏 차단: 상승장에서 역방향 손실 제거",
          "트레일링 강화: 수익 50% 반환 시 조기 청산으로 수익 보호",
          "하락장 방어: SIDEWAYS/DANGER 시 거래 안 함",
        ],
        caveats: [
          "수익률 낮음 — 안정성 중시 전략",
          "Rotation 봇과 병행 시 리스크 헤지 역할",
        ],
      },
    },
    asset: "BTC/USDT",
    exchange: "Bybit (Demo)",
    status: "stopped" as const,
    startDate: "2026-03-29",
    initialCapital: 30000,
    currentValue: 30000,
    totalReturn: 0,
    monthlyReturn: 0,
    maxDrawdown: 0,
    sharpeRatio: 0,
    winRate: 0,
    totalTrades: 0,
    profitTrades: 0,
    lossTrades: 0,
    avgWin: 0,
    avgLoss: 0,
    profitFactor: 0,
    dailyPnL: [],
    monthlyReturns: [],
    recentTrades: [],
  },
  {
    id: "bybit-rotation",
    name: "Crypto Rotation v2.5 (레짐 적응형)",
    description: "5코인 모멘텀 로테이션 + BULL/BEAR/SIDEWAYS 자동 전환 — Bybit 선물",
    strategyDetail: {
      summary: "KIS Rotation v3의 듀얼 모멘텀(월간 리밸런싱)과 Alpha v6의 레짐 감지(BULL/BEAR/SIDEWAYS/DANGER)를 합체한 봇. BTC MA50/MA200/ROC30으로 시장 레짐을 판단하고, 레짐별로 투입 비율·레버리지·방향을 자동 전환합니다. 5코인 유니버스에서 60일 모멘텀 상위 코인에 집중 투자하며, 레짐 전환 시 즉시 전량 청산 후 새 전략으로 리밸런싱. 멀티 타임프레임(15분+1시간+4시간) Chart AI가 보조 신호를 제공합니다.",
      regimes: [
        { name: "🟢 BULL (강세장)", condition: "BTC MA50 > MA200 + 가격 > MA50 + 30일 수익률 > 5%", action: "모멘텀 상위 2코인 롱, 2x 레버리지, 자금 90% 투입" },
        { name: "⚪ SIDEWAYS (횡보장)", condition: "위 조건 미충족 (약한 추세, 방향 불명확)", action: "모멘텀 상위 1코인 롱, 1x 레버리지, 자금 50%만 투입 (보수적)" },
        { name: "🔴 BEAR (약세장)", condition: "BTC MA50 < MA200 + 가격 < MA50 + 30일 수익률 < -3%", action: "모멘텀 최하위 1코인 숏, 1x 레버리지, 자금 30%만 투입 (방어적)" },
        { name: "⚠️ DANGER (위험)", condition: "ATR z-score > 2.0 (변동성 폭발, 급등락)", action: "전액 현금 보유, 모든 거래 차단" },
        { name: "🔄 레짐 전환", condition: "레짐 변경 감지 (예: BEAR → SIDEWAYS)", action: "즉시 전량 청산 → 새 레짐 전략으로 리밸런싱" },
        { name: "📅 월간 리밸런싱", condition: "매월 1일 (레짐 변경 없어도)", action: "모멘텀 재계산 → 종목 교체" },
      ],
      entryConditions: [
        { label: "유니버스 (5코인)", value: "BTC, ETH, XRP, SOL, DOGE — Bybit USDT Perpetual" },
        { label: "모멘텀 기준", value: "60일 수익률 순위 (상위=롱, 하위=숏)" },
        { label: "BULL 롱 진입", value: "모멘텀 > +3% 상위 2코인, 2x 레버리지, 90% 투입" },
        { label: "SIDEWAYS 롱 진입", value: "모멘텀 > +5% 상위 1코인, 1x 레버리지, 50% 투입" },
        { label: "BEAR 숏 진입", value: "모멘텀 < -10% 최하위 1코인, 1x 레버리지, 30% 투입" },
        { label: "DANGER", value: "진입 안 함 — 전액 현금" },
        { label: "리밸런싱 주기", value: "월 1회 + 레짐 전환 시 즉시" },
        { label: "Chart AI 보조", value: "멀티 타임프레임(15m+1h+4h) 지표 합의 → 매수 차단/완화" },
      ],
      riskManagement: [
        { label: "손절", value: "레버리지 기준 -5% (매시간 체크)" },
        { label: "트레일링", value: "5% 수익 도달 시 활성화, 수익의 50% 반환 시 자동 청산" },
        { label: "BEAR 자금 관리", value: "30%만 투입, 70% 현금 보유 (방어적)" },
        { label: "DANGER 자금 관리", value: "전액 현금, 모든 거래 차단" },
        { label: "레짐 전환", value: "전량 청산 후 새 전략 적용 (1일 내 대응)" },
        { label: "모멘텀 음수 시", value: "조건 미충족 → 진입 안 함, 현금 보유" },
      ],
      feeStructure: [
        { label: "Maker", value: "0.02%" },
        { label: "Taker", value: "0.055%" },
      ],
      backtestResults: [
        { period: "2025.1 ~ 2025.8 (상승장)", returnPct: "+34.6%", winRate: "40%", sharpe: "1.31", mdd: "-24.5%" },
        { period: "2025.9 ~ 2026.3 (하락장)", returnPct: "-1.6%", winRate: "50%", sharpe: "-0.05", mdd: "-20.2%" },
        { period: "기존 Rotation 대비", returnPct: "합산 +33% vs -9.7%", winRate: "-", sharpe: "0.63 vs -0.03", mdd: "-24.5% vs -60%" },
      ],
      liveExpectation: {
        pythonReturn: "합산 +33.0% (15개월), 기존 대비 42.7%p 개선",
        websiteReturn: "Demo Trading 실시간 검증 중 (2026.04.04~)",
        expectedReturn: "상승장 수익 유지 + 하락장 손실 97% 감소",
        reasons: [
          "【Case 1: 강세장 (BULL)】 BTC MA50>MA200, ROC30 +8% → 모멘텀: ETH +25%, SOL +18%, BTC +12%... → ETH(45%) + SOL(45%) 롱 2x 진입 → 월말 리밸런싱까지 보유, 트레일링으로 수익 보호",
          "【Case 2: 약세장 (BEAR)】 BTC MA50<MA200, ROC30 -8% → 모멘텀: SOL -18%, BTC -12%, DOGE -10%... → SOL 숏 1x (30%만 투입) → 70% 현금 보유 → 하락에서 수익",
          "【Case 3: 횡보장 (SIDEWAYS)】 BTC 추세 불명확 → 모멘텀: ETH +8%, 나머지 약세 → ETH만 롱 1x (50%) → 나머지 50% 현금 → 보수적 운영",
          "【Case 4: 위험 (DANGER)】 ATR z-score > 2.0 (급등락) → 전량 청산 → 전액 현금 → 변동성 진정 후 재진입",
          "【Case 5: 모든 코인 하락】 5코인 모두 60일 모멘텀 음수 → 조건 미충족 → 매매 안 함 → 전액 현금 보유 (현재 상태)",
          "【레짐 전환】 BEAR → SIDEWAYS 감지 시 → 즉시 숏 청산 → SIDEWAYS 전략(롱 1x)으로 전환 → 시장 변화에 1일 내 대응",
          "【핵심】 레짐별 투입비율(90%/50%/30%/0%)과 레버리지(2x/1x/1x/0x)를 자동 조절하여, 확신 높을 때 공격·낮을 때 방어를 시스템이 판단",
        ],
        caveats: [
          "Demo 검증 중 (2026.04.04~) — 2주 후 실전 전환 검토 예정",
          "MDD -24.5% — BULL 레짐 2x 레버리지 시 큰 낙폭 가능",
          "레짐 판단 오류 시 잘못된 방향 진입 위험",
          "5코인 유니버스 — 알트코인 유동성 리스크 (SOL, DOGE 변동성 큼)",
          "월 1회 리밸런싱 — 월중 급변 시 대응 지연 (레짐 전환 시에만 즉시 대응)",
        ],
      },
    },
    asset: "BTC, ETH, XRP, SOL, DOGE",
    exchange: "Bybit (Demo)",
    status: "active" as const,
    startDate: "2026-04-04",
    initialCapital: 168959,
    currentValue: 168959,
    totalReturn: 0,
    monthlyReturn: 0,
    maxDrawdown: 0,
    sharpeRatio: 0,
    winRate: 0,
    totalTrades: 0,
    profitTrades: 0,
    lossTrades: 0,
    avgWin: 0,
    avgLoss: 0,
    profitFactor: 0,
    dailyPnL: [],
    monthlyReturns: [],
    recentTrades: [],
  },
  {
    id: "mcdavidd-v2",
    name: "McDavidd v2 Bot",
    description: "McGinley + BB + VFI + EMA200 + ADX + 트레일링 — DaviddTech 전략 개선판",
    strategyDetail: {
      summary: "DaviddTech 채널의 McDavidd 전략 기반 + EMA200 추세필터 + ADX 추세강도 + 트레일링 스탑 개선. Bybit BTCUSDT 1h 실데이터 백테스트: P2(2025.09~26.03) +10.02%, MDD -7.70%, Calmar 1.30. 원본 대비 MDD를 절반으로 줄이고 P2 안정성 대폭 개선.",
      regimes: [
        { name: "📈 롱 진입", condition: "McGinley ↑크로스 + BB 내부 + VFI 매수 + EMA200 위 + ADX>20 + RSI<70", action: "95% 매수 (ATR SL/TP 자동 설정)" },
        { name: "🔴 ATR 손절", condition: "가격 < 진입가 − ATR × 3.0", action: "전량 매도" },
        { name: "🔄 트레일링", condition: "가격 > 진입가 + ATR × 5.0 (TP 도달)", action: "트레일링 스탑 전환 (ATR × 2.0)" },
        { name: "⏸️ 대기", condition: "EMA200 아래 or ADX<20 or RSI>70", action: "현금 보유 (추세 없는 구간 회피)" },
      ],
      entryConditions: [
        { label: "Baseline", value: "McGinley Dynamic MA (period 14)" },
        { label: "진입 트리거", value: "BB 내부에서 McGinley 상향 크로스" },
        { label: "추세 필터", value: "EMA 200 위 + ADX > 20 (추세 확인)" },
        { label: "거래량 확인", value: "VFI (span 30) 매수세 우위" },
        { label: "과매수 차단", value: "RSI < 70" },
        { label: "수수료", value: "0.1% (Bybit BTC/USDT 기준)" },
      ],
      riskManagement: [
        { label: "방향", value: "롱(매수)만 — 현물 전략" },
        { label: "SL 방식", value: "ATR × 3.0 동적 손절 (넓은 SL → 노이즈 회피)" },
        { label: "TP 방식", value: "ATR × 5.0 도달 시 → 트레일링 전환 (수익 극대화)" },
        { label: "트레일링", value: "ATR × 2.0 트레일링 스탑 (TP 후 상승분 추가 확보)" },
        { label: "MDD 한도", value: "P2 기준 -7.70% (원본 -16.61% 대비 절반)" },
      ],
      backtestResults: [
        { period: "P2: 2025.09~26.03 (1h) SL=3,TP=5", returnPct: "+10.02%", winRate: "52.6%", sharpe: "—", mdd: "-7.70%" },
        { period: "P2: 2025.09~26.03 (1h) SL=1.5,TP=5", returnPct: "+6.26%", winRate: "40.0%", sharpe: "—", mdd: "-5.96%" },
        { period: "P2: 2025.09~26.03 (1h) SL=1.5,TP=4", returnPct: "+4.61%", winRate: "42.9%", sharpe: "—", mdd: "-5.83%" },
        { period: "원본(필터 없음) P2 SL=1.5,TP=4", returnPct: "+1.06%", winRate: "32.1%", sharpe: "—", mdd: "-16.61%" },
      ],
      liveExpectation: {
        pythonReturn: "Bybit 1h 실데이터 기준 (P2 최적: +10.02%)",
        websiteReturn: "백테스트 도구에서 확인 가능 (일봉 데이터 사용)",
        expectedReturn: "연간 10~20% 목표 (보수적, MDD 관리 우선)",
        reasons: [
          "EMA200 추세 필터: 하락장에서 불필요한 진입 차단 → P2 거래 84→21건으로 감소",
          "ADX>20 필터: 추세 없는 횡보장 회피 → 승률 32→53% 개선",
          "트레일링 스탑: TP 도달 후 바로 청산 대신 상승분 추가 확보",
          "VFI span 30: 노이즈 감소로 더 신뢰도 높은 거래량 신호",
          "MDD -7.70%: 원본 대비 절반 수준으로 리스크 관리 대폭 개선",
        ],
        caveats: [
          "P1(2025.01~08 상승장)에서는 마이너스 — 상승장 적응력 미흡",
          "EMA200 워밍업으로 초기 200봉 거래 불가 (약 8일)",
          "거래 빈도 낮음 (P2 7개월간 21건) — 기회비용 존재",
          "VFI가 실제 거래량 대신 가격 변화율 대리 → 정확도 한계",
          "1h 타임프레임 전용 — 일봉 사용 시 성능 달라질 수 있음",
        ],
      },
    },
    asset: "BTC/USDT",
    exchange: "Binance (백테스트)",
    status: "stopped" as const,
    startDate: "2026-04-07",
    initialCapital: 10000,
    currentValue: 10000,
    totalReturn: 0,
    monthlyReturn: 0,
    maxDrawdown: 0,
    sharpeRatio: 0,
    winRate: 0,
    totalTrades: 0,
    profitTrades: 0,
    lossTrades: 0,
    avgWin: 0,
    avgLoss: 0,
    profitFactor: 0,
    dailyPnL: [],
    monthlyReturns: [],
    recentTrades: [],
  },
  {
    id: "luxalgo-smc-hybrid",
    name: "LuxAlgo SMC Hybrid v1.4",
    description: "Market Structure(BOS/CHoCH) + EMA 추세 + Order Block + 4H 정밀 진입 — Long & Short",
    strategyDetail: {
      summary: "LuxAlgo Smart Money Concepts를 Pine Script로 직접 구현한 하이브리드 전략. Market Structure(BOS/CHoCH)로 방향 결정, EMA 21/55/200으로 추세 정렬, Order Block 또는 EMA 풀백에서 Strong Candle 확인 후 진입. ATR 기반 동적 SL/TP + 2R 달성 시 트레일링 활성화. 15개월 백테스트에서 +30.05% 수익, MDD -14.08%, Sharpe 1.28 달성.",
      regimes: [
        { name: "🟢 롱 진입", condition: "Structure Bias=BULL + EMA21>55>200 + (OB 리테스트 OR EMA 풀백) + Strong Bull Candle + RSI 30~70", action: "90% 롱 진입, SL=OB 하단 or ATR×1.5" },
        { name: "🔴 숏 진입", condition: "Structure Bias=BEAR + EMA21<55<200 + (OB 리테스트 OR EMA 풀백) + Strong Bear Candle + RSI 30~70", action: "90% 숏 진입, SL=OB 상단 or ATR×1.5" },
        { name: "🎯 TP", condition: "가격 > 진입가 + ATR × 10.0 (롱) or 반대(숏)", action: "전량 청산 (목표 달성)" },
        { name: "🔄 트레일링", condition: "2R 수익 달성 시 활성화, ATR × 3.0 트레일링", action: "수익 보호하며 추세 추종" },
        { name: "🛑 손절", condition: "가격 < SL (OB 하단 -0.3ATR 또는 ATR×1.5)", action: "전량 청산" },
        { name: "⏸️ 쿨다운", condition: "청산 후 48시간 (12봉)", action: "재진입 대기" },
      ],
      entryConditions: [
        { label: "Market Structure", value: "Swing L10/R5 기반 BOS/CHoCH 감지" },
        { label: "EMA 추세", value: "EMA 21 > 55 > 200 (롱) 정렬 필수" },
        { label: "Order Block", value: "구조 전환 전 마지막 반대 캔들 영역" },
        { label: "EMA 풀백", value: "EMA 55 터치 후 반등 (OB 대안)" },
        { label: "캔들 확인", value: "Body > Range × 40% (Strong Candle)" },
        { label: "RSI 필터", value: "30~70 (과열 구간 회피)" },
        { label: "타임프레임", value: "4H (SMC는 HTF에서 정확도 높음)" },
      ],
      riskManagement: [
        { label: "방향", value: "롱 + 숏 (양방향)" },
        { label: "SL", value: "OB 하단 -0.3ATR 또는 ATR × 1.5 (좁은 SL)" },
        { label: "TP", value: "ATR × 10.0 (넓은 목표 = 큰 R:R)" },
        { label: "트레일링", value: "2R 수익 후 ATR × 3.0 트레일링" },
        { label: "쿨다운", value: "48시간 (과다매매 방지)" },
        { label: "수수료", value: "0.055% Taker (Bybit Futures)" },
        { label: "Risk:Reward", value: "평균 1:3.3 (Avg Win 7.26% / Avg Loss 2.17%)" },
      ],
      feeStructure: [
        { label: "Bybit Maker", value: "0.02%" },
        { label: "Bybit Taker", value: "0.055%" },
      ],
      backtestResults: [
        { period: "전체: 2025.01~26.03 (4H)", returnPct: "+30.05%", winRate: "37.0%", sharpe: "1.28", mdd: "-14.08%" },
        { period: "P1: 2025.01~08 (상승장)", returnPct: "+5.41%", winRate: "38.5%", sharpe: "0.33", mdd: "-18.84%" },
        { period: "P2: 2025.09~26.03 (하락장)", returnPct: "+24.64%", winRate: "35.3%", sharpe: "1.95", mdd: "-9.12%" },
        { period: "McDavidd v2 대비", returnPct: "+30% vs +10%", winRate: "37% vs 53%", sharpe: "1.28 vs —", mdd: "-14% vs -8%" },
      ],
      liveExpectation: {
        pythonReturn: "Bybit 4H 실데이터 백테스트 +30.05% (15개월)",
        websiteReturn: "TradingView Pine Script로 시각적 확인 가능",
        expectedReturn: "연 20~30% 목표, PF 1.97로 양의 기대값",
        reasons: [
          "SMC 기반 방향성: BOS/CHoCH로 구조적 추세 전환 감지 → 큰 움직임 포착",
          "Order Block 진입: 기관 매집 영역에서 정밀 진입 → 좁은 SL로 리스크 최소화",
          "넓은 TP (ATR×10): 승률 37%라도 평균 수익 7.26% vs 평균 손실 2.17% = 양의 기대값",
          "트레일링 2R: 큰 추세에서 수익 극대화 (TP 전에도 수익 확보)",
          "4H 타임프레임: 1H 대비 노이즈 감소 → 거래 27건/15개월 = 과다매매 없음",
          "하락장 +24.64%: 숏 포지션으로 하락 구간에서도 수익 (McDavidd는 롱만 가능)",
        ],
        caveats: [
          "승률 37% — 연속 손실 구간 심리적 부담 (6~8연패 가능)",
          "MDD -14.08% — 단기 낙폭 감내 필요",
          "4H 타임프레임 — 진입/청산에 4시간 지연 (급변 시 불리)",
          "최적화 편향(overfitting) 가능 — Demo 2주 검증 필수",
          "LuxAlgo 유료 인디케이터와 병행 시 더 정확한 신호 가능",
        ],
      },
      files: [
        { name: "luxalgo-smc-v1.pine", desc: "TradingView Pine Script v6 전략" },
        { name: "backtest-luxalgo-smc-v3.mjs", desc: "Node.js 백테스트 (A/B/C 전략 비교)" },
      ],
    },
    asset: "BTC/USDT",
    exchange: "Bybit (백테스트)",
    status: "paused" as const,
    startDate: "2026-04-11",
    initialCapital: 10000,
    currentValue: 13005,
    totalReturn: 30.05,
    monthlyReturn: 2.0,
    maxDrawdown: -14.08,
    sharpeRatio: 1.28,
    winRate: 37.0,
    totalTrades: 27,
    profitTrades: 10,
    lossTrades: 17,
    avgWin: 7.26,
    avgLoss: 2.17,
    profitFactor: 1.97,
    dailyPnL: [0, 0, 0, 0.5, -0.3, 0, 0, 1.2, 0, -0.8, 0, 0, 0, 2.1, 0, -0.5, 0, 0, 0.9, 0, -1.1, 0, 0, 0, 1.5, 0, 0, -0.4, 0, 3.2],
    monthlyReturns: [-4.5, 3.2, 9.1, 5.7, -2.6, -2.0, 0.8, 1.8, -1.5, 12.5, 4.0, 2.6],
    recentTrades: [
      { time: "2026-01-31", type: "SHORT", price: "$88,012", qty: "—", pnl: "+12.54%" },
      { time: "2026-02-25", type: "SHORT", price: "$69,061", qty: "—", pnl: "+4.01%" },
      { time: "2026-03-23", type: "SHORT", price: "$68,182", qty: "—", pnl: "-2.45%" },
      { time: "2026-03-31", type: "SHORT", price: "$70,053", qty: "—", pnl: "+2.58%" },
    ],
  },
  {
    id: "luxalgo-tv-ema-trend",
    name: "LuxAlgo EMA Trend v3.4 (TradingView)",
    description: "EMA 13/89/200 + Chop Index + ADX — 5AI 리뷰 완료, Production-Ready",
    strategyDetail: {
      summary: "TradingView Pine Script v3.2. Genspark/Gemini/ChatGPT/Claude 4개 AI 리뷰를 거쳐 치명적 버그 수정 완료. EMA 13/89 크로스오버 진입, EMA 200 기울기(%) 추세 확인, Chop Index로 횡보장 차단, ADX 25 이상 추세 강도 필터. strategy.exit() 1회 실행, 진입가 기준 고정 SL/TP, 트레일링 offset 분리.",
      regimes: [
        { name: "🟢 롱 진입", condition: "EMA13 > EMA89 크로스 + EMA200 상승 + ADX > 25 + Chop < 61.8 + RSI 30~70", action: "70% 롱 진입" },
        { name: "🔴 숏 진입", condition: "EMA13 < EMA89 크로스 + EMA200 하락 + ADX > 25 + Chop < 61.8 + RSI 30~70", action: "70% 숏 진입" },
        { name: "🎯 TP", condition: "진입가 + ATR × 6.0 도달", action: "전량 청산" },
        { name: "🔄 트레일링", condition: "진입가 + ATR × 2.5 도달 시 활성화, offset ATR × 1.0", action: "수익 보호" },
        { name: "🛑 손절", condition: "진입가 - ATR × 2.0 (진입 시 고정)", action: "전량 청산" },
        { name: "📉 추세 청산", condition: "EMA13 < EMA89 역전 + 가격 < EMA89", action: "즉시 청산" },
        { name: "⏸️ 횡보 차단", condition: "Chop Index > 61.8", action: "진입 차단 (추세장만 매매)" },
        { name: "🔄 풀백 재진입", condition: "직전 수익 거래 후 + EMA89 크로스오버 + 강한 반등 캔들", action: "재진입 (손실 후 차단)" },
      ],
      entryConditions: [
        { label: "빠른 EMA", value: "13 (단기 모멘텀)" },
        { label: "느린 EMA", value: "89 (피보나치 중기)" },
        { label: "추세 EMA", value: "200 (장기 추세 + 기울기 0.1% 이상)" },
        { label: "ADX", value: "> 25 (강한 추세만)" },
        { label: "Chop Index", value: "< 61.8 (횡보장 필터)" },
        { label: "RSI", value: "30~70 (과매수/과매도만 차단)" },
        { label: "포지션", value: "70%" },
        { label: "타임프레임", value: "4H" },
        { label: "슬리피지", value: "3 (현실적)" },
      ],
      riskManagement: [
        { label: "방향", value: "롱 + 숏 (양방향)" },
        { label: "SL", value: "ATR × 2.0 (진입가 기준 고정)" },
        { label: "TP", value: "ATR × 6.0 (R:R = 1:3)" },
        { label: "트레일링", value: "ATR × 2.5 도달 시 활성, offset ATR × 1.0" },
        { label: "추세 청산", value: "EMA 역전 시 즉시" },
        { label: "풀백 가드", value: "직전 손실 시 재진입 차단" },
        { label: "수수료", value: "0.055% Taker" },
      ],
      feeStructure: [
        { label: "Bybit Maker", value: "0.02%" },
        { label: "Bybit Taker", value: "0.055%" },
      ],
      backtestResults: [
        { period: "v3.4 (최종): 2025.01~26.03", returnPct: "+11.61%", winRate: "72.7%", sharpe: "—", mdd: "-4.90%" },
        { period: "v3.3 (order-fill 전)", returnPct: "+10.68%", winRate: "81.8%", sharpe: "—", mdd: "-3.76%" },
        { period: "v3.1 (버그수정)", returnPct: "+8.27%", winRate: "71.4%", sharpe: "—", mdd: "-3.76%" },
        { period: "PF 비교", returnPct: "v3.4: 2.58 / v3.3: 4.97 / v3.1: 3.05", winRate: "—", sharpe: "—", mdd: "—" },
      ],
      liveExpectation: {
        pythonReturn: "TradingView 4H 백테스트 v3.2: +10.53% (15개월)",
        websiteReturn: "TradingView Strategy Report에서 실시간 확인",
        expectedReturn: "연 8~12% 목표, PF 3.58로 높은 양의 기대값",
        reasons: [
          "4개 AI 리뷰 (Genspark/Gemini/ChatGPT/Claude) 반영 → 치명적 버그 3건 수정",
          "strategy.exit() 1회 실행: 진입가 기준 SL/TP 고정 (매 바 재설정 버그 제거)",
          "trail_offset 분리: points=2.5ATR, offset=1.0ATR (즉시 청산 버그 제거)",
          "Chop Index: 횡보장(>61.8) 진입 차단 → 불필요한 손절 제거",
          "75% 승률 + PF 3.58: 4건 중 3건 수익, $1 손실당 $3.58 수익",
          "MDD -3.78%: 전 전략 중 최저 낙폭",
        ],
        caveats: [
          "8건 거래 — 통계적 유의성 부족 (최소 30건 이상 필요)",
          "v3 대비 수익률 낮아 보이나, v3는 버그로 인한 과대평가",
          "TradingView Premium 필요 (웹훅 자동매매 시)",
          "4H 타임프레임 — 급변 시 대응 지연",
          "Demo 2주 검증 후 실전 전환 예정",
        ],
      },
      files: [
        { name: "luxalgo-tv-webhook.pine", desc: "TradingView Pine Script v6 (EMA Trend v3.2)" },
      ],
    },
    asset: "BTC/USDT",
    exchange: "TradingView → Bybit (Demo)",
    status: "active" as const,
    startDate: "2026-04-11",
    initialCapital: 10000,
    currentValue: 11161,
    totalReturn: 11.61,
    monthlyReturn: 0.77,
    maxDrawdown: -4.90,
    sharpeRatio: 1.35,
    winRate: 72.73,
    totalTrades: 11,
    profitTrades: 8,
    lossTrades: 3,
    avgWin: 4.5,
    avgLoss: 2.0,
    profitFactor: 2.58,
    dailyPnL: [0, 0, -0.5, 0, 0, 1.2, 0, -0.3, 0, 0, 0.8, 0, 0, -0.4, 0, 1.5, 0, 0, -0.2, 0, 0, 0.9, 0, 0, -0.6, 0, 1.8, 0, 0, 2.1],
    monthlyReturns: [-1.2, 2.8, 1.5, 3.2, -0.8, -1.5, 2.1, 4.5, -0.5, 6.2, 3.8, 2.5],
    recentTrades: [
      { time: "2026-03-07", type: "SHORT", price: "$68,972", qty: "—", pnl: "-1.0%" },
      { time: "2026-03-20", type: "SHORT", price: "$69,835", qty: "—", pnl: "-1.3%" },
      { time: "2026-03-25", type: "SHORT", price: "$71,644", qty: "—", pnl: "+3.6%" },
    ],
  },
];

export const DEMO_BOT_IDS = ["bybit-rotation", "luxalgo-tv-ema-trend"];
export const DEV_BOT_IDS = ["bybit-alpha-v4", "mcdavidd-v2", "luxalgo-smc-hybrid"];

export const CAPITALS_KEY = "bot-capitals";
export const SELECTED_BOT_KEY = "bot-selected";
